#!/bin/sh

case "$1" in
  configure)
    if ! [ `getent passwd thresh` ]; then
      adduser --system --group thresh
    fi

    #Restart does not pick up upstart job config changes stop/start is needed
    stop mon-thresh
    start mon-thresh
  ;;
esac

exit 0
