#!/bin/sh

case "$1" in
  configure)
    chmod +x /etc/init.d/monasca-thresh
    if ! [ `getent passwd thresh` ]; then
      adduser --system --group thresh
    fi

    #Restart does not pick up upstart job config changes stop/start is needed
    service monasca-thresh stop
    service monasca-thresh start
  ;;
esac

exit 0
